# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 17:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
